module.exports = {
    id: 20,
    name: "Jennifer Jones",
    wins: 2,
    losses: 0,
    ties: 0,
    total_points: 9,
    total_ends_played: 18,
    hammer_ends_count: 8,
    hammer_steal_count: 3,
    hammer_blank_count: 2,
    hammer_1_point_count: 3,
    hammer_2_point_count: 3,
    hammer_3_point_count: 0,
    hammer_4_point_count: 0,
    hammer_5_point_count: 0,
    hammer_6_point_count: 0,
    hammer_7_point_count: 0,
    hammer_8_point_count: 0,
    stolen_end_count: 0,
    forced_end_count: 1,
    avg_points_conceded: 1.5,
    lead_player_id: 19,
    lead_player_name: "Dawn Askin",
    second_player_id: 21,
    second_player_name: "Jocelyn Peterman",
    third_player_id: 23,
    third_player_name: "Kaitlyn Lawes",
    fourth_player_id: 22,
    fourth_player_name: "Jennifer Jones",
    fifth_player_id: null,
    fifth_player_name: null,
    sixth_player_id: null,
    sixth_player_name: null,
    seventh_player_id: null,
    seventh_player_name: null,
    team_avg: 3.15151515151515,
};
